# Host: localhost  (Version: 5.5.54)
# Date: 2018-06-10 16:24:59
# Generator: MySQL-Front 5.3  (Build 1.27)

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;
/*!40101 SET SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES */;
/*!40103 SET SQL_NOTES='ON' */;

#
# Source for table "purchase_sell_order"
#

DROP TABLE IF EXISTS `purchase_sell_order`;
CREATE TABLE `purchase_sell_order` (
  `purchase_id` int(11) NOT NULL DEFAULT '0',
  `sell_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`purchase_id`,`sell_id`),
  KEY `sell_id` (`sell_id`),
  CONSTRAINT `purchase_sell_order_ibfk_1` FOREIGN KEY (`purchase_id`) REFERENCES `ord` (`Id`),
  CONSTRAINT `purchase_sell_order_ibfk_2` FOREIGN KEY (`sell_id`) REFERENCES `ord` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
